import random

templates = [
    "**** ahead",
    "no **** ahead",
    "**** required ahead",
    "be wary of ****",
    "try ****",
    "likely ****",
    "first off, ****",
    "seek ****",
    "still no ****...",
    "why is it always ****?",
    "if only I had a ****...",
    "didn't expect ****...",
    "visions of ****...",
    "could this be a ****?",
    "time for ****",
    "****, O ****",
    "behold, ****!",
    "offer ****",
    "praise the ****!",
    "let there be ****",
    "ahh, ****...",
    "****",
    "****!",
    "****?",
    "****..."
]

words = [
    "enemy",
    "weak foe",
    "strong foe",
    "monster",
    "dragon",
    "boss",
    "sentry",
    "group",
    "pack",
    "decoy",
    "undead",
    "soldier",
    "knight",
    "cavalier",
    "archer",
    "sniper",
    "mage",
    "ordnance",
    "monarch",
    "lord",
    "demi-human",
    "outsider",
    "giant",
    "horse",
    "dog",
    "wolf",
    "rat",
    "beast",
    "bird",
    "raptor",
    "snake",
    "crab",
    "prawn",
    "octopus",
    "bug",
    "scarab",
    "slug",
    "wraith",
    "skeleton",
    "monstrosity",
    "ill-omened creature",
    "Tarnished",
    "warrior",
    "swordfighter",
    "knight",
    "samurai",
    "sorcerer",
    "cleric",
    "sage",
    "merchant",
    "teacher",
    "master",
    "friend",
    "lover",
    "old dear",
    "old codger",
    "angel",
    "fat coinpurse",
    "pauper",
    "good sort",
    "wicker sort",
    "plump sort",
    "skinny sort",
    "lovable sort",
    "pathetic sort",
    "strange sort",
    "nimble sort",
    "laggardly sort",
    "invisible sort",
    "unfathomable sort",
    "giant sort",
    "sinner",
    "thief",
    "liar",
    "dastard",
    "traitor",
    "pair",
    "trio",
    "noble",
    "aristocrat",
    "hero",
    "champion",
    "monarch",
    "lord",
    "god",
    "item",
    "necessary item",
    "precious item",
    "something",
    "something incredible",
    "treasure chest",
    "corpse",
    "coffin",
    "trap",
    "armament",
    "shield",
    "bow",
    "projectile weapon",
    "armor",
    "talisman",
    "skill",
    "sorcery",
    "incantation",
    "map",
    "material",
    "flower",
    "grass",
    "tree",
    "fruit",
    "seed",
    "mushroom",
    "tear",
    "crystal",
    "butterfly",
    "bug",
    "dung",
    "grace",
    "door",
    "key",
    "ladder",
    "lever",
    "lift",
    "spiritspring",
    "sending gate",
    "stone astrolabe",
    "Birdseye Telescope",
    "message",
    "bloodstain",
    "Erdtree",
    "Elden Ring",
    "close-quarters battle",
    "ranged battle",
    "horseback battle",
    "luring out",
    "defeating one-by-one",
    "taking on all at once",
    "rushing in",
    "stealth",
    "mimicry",
    "confusion",
    "pursuit",
    "fleeing",
    "summoning",
    "circling around",
    "jumping off",
    "dashing through",
    "brief respite",
    "attacking",
    "jump attack",
    "running attack",
    "critical hit",
    "two-handing",
    "blocking",
    "parrying",
    "guard counter",
    "sorcery",
    "incantation",
    "skill",
    "summoning",
    "throwing",
    "healing",
    "running",
    "rolling",
    "backstepping",
    "jumping",
    "crouching",
    "target lock",
    "item crafting",
    "gesturing",
    "morning",
    "noon",
    "evening",
    "night",
    "clear sky",
    "overcast",
    "rain",
    "storm",
    "mist",
    "snow",
    "patrolling",
    "procession",
    "crowd",
    "surprise attack",
    "ambush",
    "pincer attack",
    "beating to a pulp",
    "battle",
    "reinforcements",
    "ritual",
    "explosion",
    "high spot",
    "defensible spot",
    "climbable spot",
    "crossable spot",
    "bright spot",
    "dark spot",
    "open area",
    "cramped area",
    "hiding place",
    "sniping spot",
    "recon spot",
    "safety",
    "danger",
    "gorgeous view",
    "detour",
    "hidden path",
    "secret passage",
    "shortcut",
    "dead end",
    "looking away",
    "unnoticed",
    "out of stamina",
    "high road",
    "checkpoint",
    "bridge",
    "castle",
    "fort",
    "city",
    "ruins",
    "church",
    "tower",
    "camp site",
    "house",
    "cemetery",
    "underground tomb",
    "tunnel",
    "cave",
    "evergaol",
    "great tree",
    "cellar",
    "surface",
    "underground",
    "forest",
    "river",
    "lake",
    "bog",
    "mountain",
    "valley",
    "cliff",
    "waterside",
    "nest",
    "hole",
    "east",
    "west",
    "south",
    "north",
    "ahead",
    "behind",
    "left",
    "right",
    "center",
    "up",
    "down",
    "edge",
    "head",
    "stomach",
    "back",
    "arms",
    "legs",
    "rump",
    "tail",
    "core",
    "fingers",
    "physical",
    "standard",
    "striking",
    "slashing",
    "piercing",
    "fire",
    "lightning",
    "magic",
    "holy",
    "poison",
    "toxic",
    "scarlet rot",
    "blood loss",
    "frost",
    "sleep",
    "madness",
    "death",
    "life",
    "Death",
    "light",
    "dark",
    "stars",
    "fire",
    "Order",
    "chaos",
    "joy",
    "wrath",
    "suffering",
    "sadness",
    "comfort",
    "bliss",
    "misfortune",
    "good fortune",
    "bad luck",
    "hope",
    "despair",
    "victory",
    "defeat",
    "research",
    "faith",
    "abundance",
    "rot",
    "loyalty",
    "injustice",
    "secret",
    "opportunity",
    "pickle",
    "clue",
    "friendship",
    "love",
    "bravery",
    "vigor",
    "fortitude",
    "confidence",
    "distracted",
    "unguarded",
    "introspection",
    "regret",
    "resignation",
    "futility",
    "on the brink",
    "betrayal",
    "revenge",
    "destruction",
    "recklessness",
    "calmness",
    "vigilance",
    "tranquility",
    "sound",
    "tears",
    "sleep",
    "depths",
    "dregs",
    "fear",
    "sacrifice",
    "ruin",
    "good luck",
    "look carefully",
    "listen carefully",
    "think carefully",
    "well done",
    "I did it!",
    "I've failed...",
    "here!",
    "not here!",
    "don't you dare!",
    "do it!",
    "I can't take this...",
    "don't think",
    "so lonely...",
    "here again...",
    "just getting started",
    "stay calm",
    "keep moving",
    "turn back",
    "give up",
    "don't give up",
    "help me...",
    "I don't believe it...",
    "too high up",
    "I want to go home...",
    "it's like a dream...",
    "seems familiar...",
    "beautiful...",
    "you don't have the right",
    "are you ready?"
]

conjunctions = [
    " and then ",
    " or ",
    " but ",
    " therefore ",
    " in short ",
    " except ",
    " by the way ",
    " so to speak ",
    " all the more ",
    ", "
]

gestures = [
    "(Point Forwards)",
    "(Point Upwards)",
    "(Point Downwards)",
    "(Wait!)",
    "(Calm Down!)",
    "(Wave)",
    "(Beckon)",
    "(Casual Greeting)",
    "(Warm Welcome)",
    "(Bravo!)",
    "(Strength!)",
    "(Jump for Joy)",
    "(Triumphant Delight)",
    "(Fancy Spin)",
    "(Nod In Thought)",
    "(Finger Snap)",
    "(Rallying Cry)",
    "(Heartening Cry)",
    "(Bow)",
    "(Polite Bow)",
    "(As You Wish)",
    "(My Thanks)",
    "(Curtsy)",
    "(Reverential Bow)",
    "(My Lord)",
    "(What Do You Want?)",
    "(By My Sword)",
    "(Hoslow's Oath)",
    "(Fire Spur Me)",
    "(The Ring)",
    "(Erudition)",
    "(Prayer)",
    "(Desperate Prayer)",
    "(Rapture)",
    "(Inner Order)",
    "(Outer Order)",
    "(Golden Order Totality)",
    "(Extreme Repentance)",
    "(Grovel For Mercy)",
    "(Crossed Legs)",
    "(Dozing Cross-Legged)",
    "(Rest)",
    "(Sitting Sideways)",
    "(Dejection)",
    "(Patches' Crouch)",
    "(Balled Up)",
    "(Spread Out)"
]

#Templates, Words = 1
#Templates, Words, Gestures = 2
#Templates, Words, Conjunctions, Templates (2nd Line), Words(2nd Line) = 3
#Templates, Words, Conjunctions, Templates (2nd Line), Words(2nd Line), Gestures = 4
messageStructure = random.choice([1, 2, 3, 4])

if messageStructure == 1:
    message = (random.choice(templates)).replace("****", random.choice(words))
elif messageStructure == 2:
    message = (random.choice(templates)).replace("****", random.choice(words)) + " " + random.choice(gestures)
elif messageStructure == 3:
    message = (random.choice(templates)).replace("****", random.choice(words)) + random.choice(conjunctions) + (random.choice(templates)).replace("****", random.choice(words))
else:
    message = (random.choice(templates)).replace("****", random.choice(words)) + random.choice(conjunctions) + (random.choice(templates)).replace("****", random.choice(words)) + " " + random.choice(gestures)

print(message)